version: '3'
services:
    app:
      build: Docker/php
      container_name: Project
      volumes:
      - ./:/var/www
      depends_on:
        - db
    nginx:
      image: nginx:1.17
      container_name: skillup_nginx
      ports:
        - 8011:80
      volumes:
        - ./:/var/www
        - ./docker/nginx/skillup.local.conf:/etc/nginx/conf.d/skillup.local.conf
        - ./docker/nginx/chat.local.conf:/etc/nginx/conf.d/chat.local.conf
        - ./docker/nginx/lara.local.conf:/etc/nginx/conf.d/lara.local.conf
      depends_on:
        - app
    db:
      image: mysql:8.0.23
      ports:
        - 3306:3306
      volumes:
        - ./Docker/MySQL:/var/lib/mysql
      container_name: mysql
      command: --default-authentication-plugin=mysql_native_password
      environment:
        MYSQL_DATABASE: db
        MYSQL_USER: user
        MYSQL_PASSWORD: pwd
        MYSQL_ALLOW_EMPTY_PASSWORD: 1
    laraDB:
      image: mysql:8.0.23
      ports:
        - 3308:3306
      volumes:
        - ./Docker/lara-mysql:/var/lib/mysql
      container_name: lara-mysql
      command: --default-authentication-plugin=mysql_native_password
      environment:
        MYSQL_DATABASE: lara_db
        MYSQL_USER: lara_user
        MYSQL_PASSWORD: lara_pwd
        MYSQL_ALLOW_EMPTY_PASSWORD: 1
    phpmyadmin:
      image: phpmyadmin
      ports:
        - 8012:80
      environment:
        - PMA_ARBITRARY=1
        - PMA_HOST=pma.local